<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\dtop.Core\dtop.Core.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8"/>
        <PackageReference Include="Servus" Version="0.34.0"/>
    </ItemGroup>
</Project>
