services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    mem_limit: 512m

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    mem_limit: 128m

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: testpass
    mem_limit: 256m

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    mem_limit: 64m
