//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace dottop.Resources;

using System;
using System.Resources;
using System.Globalization;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[System.Diagnostics.DebuggerNonUserCodeAttribute()]
[System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Strings
{
    private static ResourceManager? resourceMan;
    private static CultureInfo? resourceCulture;

    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Strings() { }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static ResourceManager ResourceManager
    {
        get
        {
            if (resourceMan is null)
            {
                var temp = new ResourceManager("dottop.Resources.Strings", typeof(Strings).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static CultureInfo? Culture
    {
        get { return resourceCulture; }
        set { resourceCulture = value; }
    }

    internal static string TabProcesses => ResourceManager.GetString("TabProcesses", resourceCulture) ?? "";
    internal static string TabPerformance => ResourceManager.GetString("TabPerformance", resourceCulture) ?? "";
    internal static string TabServices => ResourceManager.GetString("TabServices", resourceCulture) ?? "";
    internal static string TabNetwork => ResourceManager.GetString("TabNetwork", resourceCulture) ?? "";

    internal static string PanelProcesses => ResourceManager.GetString("PanelProcesses", resourceCulture) ?? "";
    internal static string HeaderPid => ResourceManager.GetString("HeaderPid", resourceCulture) ?? "";
    internal static string HeaderName => ResourceManager.GetString("HeaderName", resourceCulture) ?? "";
    internal static string HeaderCpuPercent => ResourceManager.GetString("HeaderCpuPercent", resourceCulture) ?? "";
    internal static string HeaderRam => ResourceManager.GetString("HeaderRam", resourceCulture) ?? "";
    internal static string HeaderGroup => ResourceManager.GetString("HeaderGroup", resourceCulture) ?? "";
    internal static string GroupAll => ResourceManager.GetString("GroupAll", resourceCulture) ?? "";
    internal static string SearchHint => ResourceManager.GetString("SearchHint", resourceCulture) ?? "";
    internal static string SearchBarActiveFormat => ResourceManager.GetString("SearchBarActiveFormat", resourceCulture) ?? "";
    internal static string SearchBarInactiveFormat => ResourceManager.GetString("SearchBarInactiveFormat", resourceCulture) ?? "";

    internal static string OverlayTabOverview => ResourceManager.GetString("OverlayTabOverview", resourceCulture) ?? "";
    internal static string OverlayTabProcessTree => ResourceManager.GetString("OverlayTabProcessTree", resourceCulture) ?? "";
    internal static string OverlayTabEnvironment => ResourceManager.GetString("OverlayTabEnvironment", resourceCulture) ?? "";
    internal static string OverlayTabHandles => ResourceManager.GetString("OverlayTabHandles", resourceCulture) ?? "";
    internal static string OverlayKeyboardHints => ResourceManager.GetString("OverlayKeyboardHints", resourceCulture) ?? "";
    internal static string LoadingProcessTree => ResourceManager.GetString("LoadingProcessTree", resourceCulture) ?? "";
    internal static string LoadingEnvironmentVars => ResourceManager.GetString("LoadingEnvironmentVars", resourceCulture) ?? "";
    internal static string LoadingHandles => ResourceManager.GetString("LoadingHandles", resourceCulture) ?? "";
    internal static string NoHandleInfo => ResourceManager.GetString("NoHandleInfo", resourceCulture) ?? "";
    internal static string ProcessStatusFormat => ResourceManager.GetString("ProcessStatusFormat", resourceCulture) ?? "";

    internal static string PanelCpu => ResourceManager.GetString("PanelCpu", resourceCulture) ?? "";
    internal static string PanelRam => ResourceManager.GetString("PanelRam", resourceCulture) ?? "";
    internal static string PanelDisks => ResourceManager.GetString("PanelDisks", resourceCulture) ?? "";
    internal static string PanelNetwork => ResourceManager.GetString("PanelNetwork", resourceCulture) ?? "";
    internal static string TotalLabel => ResourceManager.GetString("TotalLabel", resourceCulture) ?? "";
    internal static string PerfStatusBar => ResourceManager.GetString("PerfStatusBar", resourceCulture) ?? "";
    internal static string DetailSectionNetwork => ResourceManager.GetString("DetailSectionNetwork", resourceCulture) ?? "";
    internal static string DetailTitle => ResourceManager.GetString("DetailTitle", resourceCulture) ?? "";
    internal static string UsedFormat => ResourceManager.GetString("UsedFormat", resourceCulture) ?? "";
    internal static string NoDisksFound => ResourceManager.GetString("NoDisksFound", resourceCulture) ?? "";
    internal static string DiskUsedFormat => ResourceManager.GetString("DiskUsedFormat", resourceCulture) ?? "";
    internal static string PanelActiveTime => ResourceManager.GetString("PanelActiveTime", resourceCulture) ?? "";
    internal static string PanelTransferRate => ResourceManager.GetString("PanelTransferRate", resourceCulture) ?? "";
    internal static string NoActiveAdapters => ResourceManager.GetString("NoActiveAdapters", resourceCulture) ?? "";

    internal static string PanelServices => ResourceManager.GetString("PanelServices", resourceCulture) ?? "";
    internal static string HeaderStatus => ResourceManager.GetString("HeaderStatus", resourceCulture) ?? "";
    internal static string HeaderStartType => ResourceManager.GetString("HeaderStartType", resourceCulture) ?? "";
    internal static string ServicesSearchHint => ResourceManager.GetString("ServicesSearchHint", resourceCulture) ?? "";
    internal static string ServicesStatusFormat => ResourceManager.GetString("ServicesStatusFormat", resourceCulture) ?? "";
    internal static string ErrorLoadingServices => ResourceManager.GetString("ErrorLoadingServices", resourceCulture) ?? "";
    internal static string ErrorFormat => ResourceManager.GetString("ErrorFormat", resourceCulture) ?? "";

    internal static string PanelNetworkConnections => ResourceManager.GetString("PanelNetworkConnections", resourceCulture) ?? "";
    internal static string HeaderLocal => ResourceManager.GetString("HeaderLocal", resourceCulture) ?? "";
    internal static string HeaderRemote => ResourceManager.GetString("HeaderRemote", resourceCulture) ?? "";
    internal static string NetworkSearchHint => ResourceManager.GetString("NetworkSearchHint", resourceCulture) ?? "";
    internal static string NetworkStatusFormat => ResourceManager.GetString("NetworkStatusFormat", resourceCulture) ?? "";
}
