<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\dtop.App\dtop.App.csproj" />
    <ProjectReference Include="..\..\src\dtop.Plugin.Docker\dtop.Plugin.Docker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NSubstitute" Version="5.*" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
