//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System.Globalization;
using System.Resources;

namespace dtop.Resources;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[System.Diagnostics.DebuggerNonUserCodeAttribute()]
[System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Strings
{
    private static ResourceManager? resourceMan;
    private static CultureInfo? resourceCulture;

    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    public Strings() { }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    public static ResourceManager ResourceManager
    {
        get
        {
            if (resourceMan is null)
            {
                var temp = new ResourceManager("dtop.Resources.Strings", typeof(Strings).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    public static CultureInfo? Culture
    {
        get { return resourceCulture; }
        set { resourceCulture = value; }
    }

    public static string TabProcesses => ResourceManager.GetString("TabProcesses", resourceCulture) ?? "";
    public static string TabPerformance => ResourceManager.GetString("TabPerformance", resourceCulture) ?? "";
    public static string TabServices => ResourceManager.GetString("TabServices", resourceCulture) ?? "";
    public static string TabNetwork => ResourceManager.GetString("TabNetwork", resourceCulture) ?? "";

    public static string PanelProcesses => ResourceManager.GetString("PanelProcesses", resourceCulture) ?? "";
    public static string HeaderPid => ResourceManager.GetString("HeaderPid", resourceCulture) ?? "";
    public static string HeaderName => ResourceManager.GetString("HeaderName", resourceCulture) ?? "";
    public static string HeaderCpuPercent => ResourceManager.GetString("HeaderCpuPercent", resourceCulture) ?? "";
    public static string HeaderRam => ResourceManager.GetString("HeaderRam", resourceCulture) ?? "";
    public static string HeaderGroup => ResourceManager.GetString("HeaderGroup", resourceCulture) ?? "";
    public static string HeaderCpuSparkline => ResourceManager.GetString("HeaderCpuSparkline", resourceCulture) ?? "";
    public static string HeaderRamBar => ResourceManager.GetString("HeaderRamBar", resourceCulture) ?? "";
    public static string HeaderMem => ResourceManager.GetString("HeaderMem", resourceCulture) ?? "";
    public static string GroupAll => ResourceManager.GetString("GroupAll", resourceCulture) ?? "";
    public static string SearchHint => ResourceManager.GetString("SearchHint", resourceCulture) ?? "";
    public static string SearchBarActiveFormat => ResourceManager.GetString("SearchBarActiveFormat", resourceCulture) ?? "";
    public static string SearchBarInactiveFormat => ResourceManager.GetString("SearchBarInactiveFormat", resourceCulture) ?? "";

    public static string OverlayTabOverview => ResourceManager.GetString("OverlayTabOverview", resourceCulture) ?? "";
    public static string OverlayTabProcessTree => ResourceManager.GetString("OverlayTabProcessTree", resourceCulture) ?? "";
    public static string OverlayTabEnvironment => ResourceManager.GetString("OverlayTabEnvironment", resourceCulture) ?? "";
    public static string OverlayTabHandles => ResourceManager.GetString("OverlayTabHandles", resourceCulture) ?? "";
    public static string OverlayKeyboardHints => ResourceManager.GetString("OverlayKeyboardHints", resourceCulture) ?? "";
    public static string KillConfirmFormat => ResourceManager.GetString("KillConfirmFormat", resourceCulture) ?? "";
    public static string LoadingProcessTree => ResourceManager.GetString("LoadingProcessTree", resourceCulture) ?? "";
    public static string LoadingEnvironmentVars => ResourceManager.GetString("LoadingEnvironmentVars", resourceCulture) ?? "";
    public static string LoadingHandles => ResourceManager.GetString("LoadingHandles", resourceCulture) ?? "";
    public static string NoHandleInfo => ResourceManager.GetString("NoHandleInfo", resourceCulture) ?? "";
    public static string ProcessStatusFormat => ResourceManager.GetString("ProcessStatusFormat", resourceCulture) ?? "";

    public static string PanelCpu => ResourceManager.GetString("PanelCpu", resourceCulture) ?? "";
    public static string PanelRam => ResourceManager.GetString("PanelRam", resourceCulture) ?? "";
    public static string PanelDisks => ResourceManager.GetString("PanelDisks", resourceCulture) ?? "";
    public static string PanelNetwork => ResourceManager.GetString("PanelNetwork", resourceCulture) ?? "";
    public static string TotalLabel => ResourceManager.GetString("TotalLabel", resourceCulture) ?? "";
    public static string PerfStatusBar => ResourceManager.GetString("PerfStatusBar", resourceCulture) ?? "";
    public static string DetailSectionNetwork => ResourceManager.GetString("DetailSectionNetwork", resourceCulture) ?? "";
    public static string DetailTitle => ResourceManager.GetString("DetailTitle", resourceCulture) ?? "";
    public static string UsedFormat => ResourceManager.GetString("UsedFormat", resourceCulture) ?? "";
    public static string NoDisksFound => ResourceManager.GetString("NoDisksFound", resourceCulture) ?? "";
    public static string DiskUsedFormat => ResourceManager.GetString("DiskUsedFormat", resourceCulture) ?? "";
    public static string PanelActiveTime => ResourceManager.GetString("PanelActiveTime", resourceCulture) ?? "";
    public static string PanelTransferRate => ResourceManager.GetString("PanelTransferRate", resourceCulture) ?? "";
    public static string NoActiveAdapters => ResourceManager.GetString("NoActiveAdapters", resourceCulture) ?? "";
    public static string PanelGpu => ResourceManager.GetString("PanelGpu", resourceCulture) ?? "";
    public static string GpuUsage => ResourceManager.GetString("GpuUsage", resourceCulture) ?? "";
    public static string GpuTemperature => ResourceManager.GetString("GpuTemperature", resourceCulture) ?? "";
    public static string GpuNoData => ResourceManager.GetString("GpuNoData", resourceCulture) ?? "";

    public static string PerfNoDisks => ResourceManager.GetString("PerfNoDisks", resourceCulture) ?? "";
    public static string PerfNoAdapters => ResourceManager.GetString("PerfNoAdapters", resourceCulture) ?? "";
    public static string PerfActiveTime => ResourceManager.GetString("PerfActiveTime", resourceCulture) ?? "";
    public static string PerfTransferRate => ResourceManager.GetString("PerfTransferRate", resourceCulture) ?? "";
    public static string HintClose => ResourceManager.GetString("HintClose", resourceCulture) ?? "";

    public static string PanelServices => ResourceManager.GetString("PanelServices", resourceCulture) ?? "";
    public static string HeaderStatus => ResourceManager.GetString("HeaderStatus", resourceCulture) ?? "";
    public static string HeaderStartType => ResourceManager.GetString("HeaderStartType", resourceCulture) ?? "";
    public static string ServicesSearchHint => ResourceManager.GetString("ServicesSearchHint", resourceCulture) ?? "";
    public static string ServicesStatusFormat => ResourceManager.GetString("ServicesStatusFormat", resourceCulture) ?? "";
    public static string ServiceDetailName => ResourceManager.GetString("ServiceDetailName", resourceCulture) ?? "";
    public static string ServiceDetailDisplay => ResourceManager.GetString("ServiceDetailDisplay", resourceCulture) ?? "";
    public static string ServiceDetailDescription => ResourceManager.GetString("ServiceDetailDescription", resourceCulture) ?? "";
    public static string ServiceNoDescription => ResourceManager.GetString("ServiceNoDescription", resourceCulture) ?? "";
    public static string ServiceDetailHints => ResourceManager.GetString("ServiceDetailHints", resourceCulture) ?? "";
    public static string ErrorLoadingServices => ResourceManager.GetString("ErrorLoadingServices", resourceCulture) ?? "";
    public static string ErrorFormat => ResourceManager.GetString("ErrorFormat", resourceCulture) ?? "";

    public static string PanelNetworkConnections => ResourceManager.GetString("PanelNetworkConnections", resourceCulture) ?? "";
    public static string HeaderProcess => ResourceManager.GetString("HeaderProcess", resourceCulture) ?? "";
    public static string HeaderLocal => ResourceManager.GetString("HeaderLocal", resourceCulture) ?? "";
    public static string HeaderRemote => ResourceManager.GetString("HeaderRemote", resourceCulture) ?? "";
    public static string NetworkSearchHint => ResourceManager.GetString("NetworkSearchHint", resourceCulture) ?? "";
    public static string NetworkStatusFormat => ResourceManager.GetString("NetworkStatusFormat", resourceCulture) ?? "";

    // Settings tab
    public static string TabSettings => ResourceManager.GetString("TabSettings", resourceCulture) ?? "";
    public static string SettingsTitle => ResourceManager.GetString("SettingsTitle", resourceCulture) ?? "";
    public static string SettingsTheme => ResourceManager.GetString("SettingsTheme", resourceCulture) ?? "";
    public static string SettingsRefreshRate => ResourceManager.GetString("SettingsRefreshRate", resourceCulture) ?? "";
    public static string SettingsDefaultSort => ResourceManager.GetString("SettingsDefaultSort", resourceCulture) ?? "";
    public static string SettingsDefaultGroup => ResourceManager.GetString("SettingsDefaultGroup", resourceCulture) ?? "";
    public static string SettingsGraphStyle => ResourceManager.GetString("SettingsGraphStyle", resourceCulture) ?? "";
    public static string SettingsLanguage => ResourceManager.GetString("SettingsLanguage", resourceCulture) ?? "";
    public static string SettingsSaved => ResourceManager.GetString("SettingsSaved", resourceCulture) ?? "";
    public static string ThemeDark => ResourceManager.GetString("ThemeDark", resourceCulture) ?? "";
    public static string ThemeLight => ResourceManager.GetString("ThemeLight", resourceCulture) ?? "";
    public static string ThemeNord => ResourceManager.GetString("ThemeNord", resourceCulture) ?? "";
    public static string SortCpu => ResourceManager.GetString("SortCpu", resourceCulture) ?? "";
    public static string SortRam => ResourceManager.GetString("SortRam", resourceCulture) ?? "";
    public static string SortName => ResourceManager.GetString("SortName", resourceCulture) ?? "";
    public static string SortPid => ResourceManager.GetString("SortPid", resourceCulture) ?? "";
    public static string GroupApps => ResourceManager.GetString("GroupApps", resourceCulture) ?? "";
    public static string GroupBackground => ResourceManager.GetString("GroupBackground", resourceCulture) ?? "";
    public static string GroupSystem => ResourceManager.GetString("GroupSystem", resourceCulture) ?? "";
    public static string GraphBlocks => ResourceManager.GetString("GraphBlocks", resourceCulture) ?? "";
    public static string GraphBraille => ResourceManager.GetString("GraphBraille", resourceCulture) ?? "";
    public static string GraphOutline => ResourceManager.GetString("GraphOutline", resourceCulture) ?? "";
    public static string GraphAscii => ResourceManager.GetString("GraphAscii", resourceCulture) ?? "";
    public static string LangSystem => ResourceManager.GetString("LangSystem", resourceCulture) ?? "";
    public static string LangDe => ResourceManager.GetString("LangDe", resourceCulture) ?? "";
    public static string LangEn => ResourceManager.GetString("LangEn", resourceCulture) ?? "";

    // Update
    public static string UpdateAvailable => ResourceManager.GetString("UpdateAvailable", resourceCulture) ?? "";
    public static string UpdateDownloading => ResourceManager.GetString("UpdateDownloading", resourceCulture) ?? "";
    public static string UpdateInstalling => ResourceManager.GetString("UpdateInstalling", resourceCulture) ?? "";
    public static string UpdateComplete => ResourceManager.GetString("UpdateComplete", resourceCulture) ?? "";
    public static string UpdateFailed => ResourceManager.GetString("UpdateFailed", resourceCulture) ?? "";
    public static string UpdatePressU => ResourceManager.GetString("UpdatePressU", resourceCulture) ?? "";
    public static string CurrentVersion => ResourceManager.GetString("CurrentVersion", resourceCulture) ?? "";

    // Docker
    public static string TabDocker => ResourceManager.GetString("TabDocker", resourceCulture) ?? "";
    public static string PanelDocker => ResourceManager.GetString("PanelDocker", resourceCulture) ?? "";
    public static string DockerStatusFormat => ResourceManager.GetString("DockerStatusFormat", resourceCulture) ?? "";
    public static string DockerNotAvailable => ResourceManager.GetString("DockerNotAvailable", resourceCulture) ?? "";
    public static string HintDockerDetailKeys => ResourceManager.GetString("HintDockerDetailKeys", resourceCulture) ?? "";
    public static string DockerLogsHeader => ResourceManager.GetString("DockerLogsHeader", resourceCulture) ?? "";
    public static string DockerLoadingLogs => ResourceManager.GetString("DockerLoadingLogs", resourceCulture) ?? "";

    // Modal/Overlay hint keys
    public static string HintProcessOverviewKeys => ResourceManager.GetString("HintProcessOverviewKeys", resourceCulture) ?? "";
    public static string HintProcessDetailKeys => ResourceManager.GetString("HintProcessDetailKeys", resourceCulture) ?? "";
    public static string HintPerfDetailKeys => ResourceManager.GetString("HintPerfDetailKeys", resourceCulture) ?? "";
    public static string HintPerfDiskDetailKeys => ResourceManager.GetString("HintPerfDiskDetailKeys", resourceCulture) ?? "";
    public static string HintPerfNetworkDetailKeys => ResourceManager.GetString("HintPerfNetworkDetailKeys", resourceCulture) ?? "";
    public static string HintServiceDetailKeys => ResourceManager.GetString("HintServiceDetailKeys", resourceCulture) ?? "";
    public static string HintNetworkDetailKeys => ResourceManager.GetString("HintNetworkDetailKeys", resourceCulture) ?? "";
    public static string HintSettingsKeys => ResourceManager.GetString("HintSettingsKeys", resourceCulture) ?? "";
    public static string HintSettingsModalKeys => ResourceManager.GetString("HintSettingsModalKeys", resourceCulture) ?? "";
}
