<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>dottop.Plugin.Abstractions</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Akka.Hosting" Version="1.5.68" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
  </ItemGroup>
</Project>
