<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RootNamespace>dottop</RootNamespace>
        <Version>0.1.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\dottop.Core\dottop.Core.csproj" />
        <ProjectReference Include="..\dottop.Windows\dottop.Windows.csproj" />
        <ProjectReference Include="..\dottop.Linux\dottop.Linux.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
        <PackageReference Include="Akka.Hosting" Version="1.5.68" />
        <PackageReference Include="Servus" Version="0.34.0" />
        <PackageReference Include="Termina" Version="0.10.2" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Resources\Strings.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Strings.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\Strings.de.resx" />
    </ItemGroup>

</Project>
