<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>dtop.Plugin.Example</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\dtop.Plugin\dtop.Plugin.csproj" />
    <ProjectReference Include="..\dtop.Core\dtop.Core.csproj" />
    <ProjectReference Include="..\dtop.App\dtop.App.csproj" />
    <ProjectReference Include="..\..\lib\termina\src\Termina\Termina.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Akka.Hosting" Version="1.5.68" />
  </ItemGroup>
</Project>
