<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>dottop.Plugin.Docker</RootNamespace>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\dottop.Plugin.Abstractions\dottop.Plugin.Abstractions.csproj" />
    <ProjectReference Include="..\dottop.Core\dottop.Core.csproj" />
    <ProjectReference Include="..\dottop.App\dottop.App.csproj" />
    <ProjectReference Include="..\..\lib\termina\src\Termina\Termina.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Docker.DotNet.Enhanced" Version="4.2.0" />
    <PackageReference Include="Akka.Hosting" Version="1.5.68" />
    <PackageReference Include="Servus" Version="0.34.0" />
  </ItemGroup>
</Project>
